export const dataFromBack = [
  {
    category: 1,
    name: 'Переобулся на зиму',
    value: 500,
    expense: true,
  },
  {
    category: 1,
    name: 'Заправка',
    value: 2500,
    expense: true,
  },
  {
    category: 1,
    name: 'Ремонт',
    value: 1000,
    expense: true,
  },
  {
    category: 1,
    name: 'Зимний омыватель',
    value: 100,
    expense: true,
  },
  {
    category: 2,
    name: 'Свинина',
    value: 5000,
    expense: true,
  },
  {
    category: 2,
    name: 'Говядина',
    value: 4500,
    expense: true,
  },
  {
    category: 2,
    name: 'Курица',
    value: 3200,
    expense: true,
  },
  {
    category: 2,
    name: 'Рыба',
    value: 2100,
    expense: true,
  },
  {
    category: 2,
    name: 'Панини',
    value: 1800,
    expense: true,
  },
  {
    category: 2,
    name: 'Кофе',
    value: 1700,
    expense: true,
  },
  {
    category: 2,
    name: 'Спагетти',
    value: 1500,
    expense: true,
  },
  {
    category: 2,
    name: 'Шоколад',
    value: 850,
    expense: true,
  },
  {
    category: 2,
    name: 'Маслины',
    value: 500,
    expense: true,
  },
  {
    category: 2,
    name: 'Зелень',
    value: 300,
    expense: true,
  },

  {
    category: 3,
    name: 'Приём врача',
    value: 300,
    expense: true,
  },
  {
    category: 3,
    name: 'Поликлиника, канцтовары',
    value: 50,
    expense: true,
  },
  {
    category: 3,
    name: 'Аптека',
    value: 1000,
    expense: true,
  },
  {
    category: 4,
    name: 'Вино',
    value: 500,
    expense: true,
  },
  {
    category: 4,
    name: 'Пиво',
    value: 200,
    expense: true,
  },
  {
    category: 5,
    name: 'Кино',
    value: 200,
    expense: true,
  },
  {
    category: 5,
    name: 'Пиццерия',
    value: 300,
    expense: true,
  },
  {
    category: 5,
    name: 'Каток',
    value: 100,
    expense: true,
  },
  {
    category: 5,
    name: 'Настольные игры',
    value: 500,
    expense: true,
  },
  {
    category: 6,
    name: 'Эпицентр',
    value: 500,
    expense: true,
  },
  {
    category: 6,
    name: 'Бытовая химия',
    value: 300,
    expense: true,
  },
  {
    category: 6,
    name: 'Полка на стену',
    value: 100,
    expense: true,
  },
  {
    category: 7,
    name: 'Наушники',
    value: 500,
    expense: true,
  },
  {
    category: 8,
    name: 'Коммуналка',
    value: 3000,
    expense: true,
  },
  {
    category: 8,
    name: 'Пополнение счета Vodafone',
    value: 150,
    expense: true,
  },
  {
    category: 8,
    name: 'Домашний интернет',
    value: 100,
    expense: true,
  },
  {
    category: 9,
    name: 'Фитнес',
    value: 600,
    expense: true,
  },
  {
    category: 9,
    name: 'Картины по номерам',
    value: 200,
    expense: true,
  },
  {
    category: 9,
    name: 'Диск на PS',
    value: 1000,
    expense: true,
  },
  {
    category: 9,
    name: 'Цветной картон для поделок',
    value: 50,
    expense: true,
  },
  {
    category: 10,
    name: 'Курсы английского',
    value: 5000,
    expense: true,
  },
  {
    category: 10,
    name: 'Платеж за курс GoIT',
    value: 3300,
    expense: true,
  },
  {
    category: 11,
    name: 'Новые сапоги',
    value: 300,
    expense: true,
  },
  {
    category: 11,
    name: 'Школьный театр',
    value: 50,
    expense: true,
  },
  {
    category: 11,
    name: 'Подарок на ДР другу',
    value: 500,
    expense: true,
  },
  {
    category: 1,
    name: 'Моя',
    value: 10000,
    expense: false,
  },
  {
    category: 1,
    name: 'Жены',
    value: 10000,
    expense: false,
  },
  {
    category: 2,
    name: '% с депозита',
    value: 1000,
    expense: false,
  },
  {
    category: 2,
    name: 'Подарок на ДР',
    value: 2000,
    expense: false,
  },
  {
    category: 2,
    name: 'Ковидная тыща',
    value: 1000,
    expense: false,
  },
];
