export const dataFromBack = [
  {
    id: 101,
    category: "Транспорт",
    name: "Переобулся на зиму",
    value: 500,
    expense: true,
  },
  {
    id: 102,
    category: "Транспорт",
    name: "Заправка",
    value: 2500,
    expense: true,
  },
  {
    id: 103,
    category: "Транспорт",
    name: "Ремонт",
    value: 1000,
    expense: true,
  },
  {
    id: 104,
    category: "Транспорт",
    name: "Зимний омыватель",
    value: 100,
    expense: true,
  },
  {
    id: 105,
    category: "Продукты",
    name: "Свинина",
    value: 5000.0,
    expense: true,
  },
  {
    id: 106,
    category: "Продукты",
    name: "Говядина",
    value: 4500,
    expense: true,
  },
  {
    id: 107,
    category: "Продукты",
    name: "Курица",
    value: 3200,
    expense: true,
  },
  {
    id: 108,
    category: "Продукты",
    name: "Рыба",
    value: 2100,
    expense: true,
  },
  {
    id: 109,
    category: "Продукты",
    name: "Панини",
    value: 1800,
    expense: true,
  },
  {
    id: 110,
    category: "Продукты",
    name: "Кофе",
    value: 1700,
    expense: true,
  },
  {
    id: 111,
    category: "Продукты",
    name: "Спагетти",
    value: 1500,
    expense: true,
  },
  {
    id: 112,
    category: "Продукты",
    name: "Шоколад",
    value: 850,
    expense: true,
  },
  {
    id: 113,
    category: "Продукты",
    name: "Маслины",
    value: 500,
    expense: true,
  },
  {
    id: 114,
    category: "Продукты",
    name: "Зелень",
    value: 300,
    expense: true,
  },

  {
    id: 115,
    category: "Здоровье",
    name: "Приём врача",
    value: 300,
    expense: true,
  },
  {
    id: 116,
    category: "Здоровье",
    name: "Поликлиника, канцтовары",
    value: 50,
    expense: true,
  },
  {
    id: 117,
    category: "Здоровье",
    name: "Аптека",
    value: 1000,
    expense: true,
  },
  {
    id: 118,
    category: "Алкоголь",
    name: "Вино",
    value: 500,
    expense: true,
  },
  {
    id: 119,
    category: "Алкоголь",
    name: "Пиво",
    value: 200,
    expense: true,
  },
  {
    id: 120,
    category: "Развлечения",
    name: "Кино",
    value: 200,
    expense: true,
  },
  {
    id: 121,
    category: "Развлечения",
    name: "Пиццерия",
    value: 300,
    expense: true,
  },
  {
    id: 122,
    category: "Развлечения",
    name: "Каток",
    value: 100,
    expense: true,
  },
  {
    id: 123,
    category: "Развлечения",
    name: "Настольные игры",
    value: 500,
    expense: true,
  },
  {
    id: 124,
    category: "Всё для дома",
    name: "Эпицентр",
    value: 500,
    expense: true,
  },
  {
    id: 125,
    category: "Всё для дома",
    name: "Бытовая химия",
    value: 300,
    expense: true,
  },
  {
    id: 126,
    category: "Всё для дома",
    name: "Полка на стену",
    value: 100,
    expense: true,
  },
  {
    id: 127,
    category: "Техника",
    name: "Наушники",
    value: 500,
    expense: true,
  },
  {
    id: 128,
    category: "Коммуналка, связь",
    name: "Коммуналка",
    value: 3000,
    expense: true,
  },
  {
    id: 129,
    category: "Коммуналка, связь",
    name: "Пополнение счета Vodafone",
    value: 150,
    expense: true,
  },
  {
    id: 130,
    category: "Коммуналка, связь",
    name: "Домашний интернет",
    value: 100,
    expense: true,
  },
  {
    id: 131,
    category: "Спорт, хобби",
    name: "Фитнес",
    value: 600,
    expense: true,
  },
  {
    id: 132,
    category: "Спорт, хобби",
    name: "Картины по номерам",
    value: 200,
    expense: true,
  },
  {
    id: 133,
    category: "Спорт, хобби",
    name: "Диск на PS",
    value: 1000,
    expense: true,
  },
  {
    id: 134,
    category: "Спорт, хобби",
    name: "Цветной картон для поделок",
    value: 50,
    expense: true,
  },
  {
    id: 135,
    category: "Образование",
    name: "Курсы английского",
    value: 5000,
    expense: true,
  },
  {
    id: 136,
    category: "Образование",
    name: "Платеж за курс GoIT",
    value: 3300,
    expense: true,
  },
  {
    id: 137,
    category: "Прочее",
    name: "Новые сапоги",
    value: 300,
    expense: true,
  },
  {
    id: 138,
    category: "Прочее",
    name: "Школьный театр",
    value: 50,
    expense: true,
  },
  {
    id: 139,
    category: "Прочее",
    name: "Подарок на ДР другу",
    value: 500,
    expense: true,
  },
  {
    id: 140,
    category: "ЗП",
    name: "Моя",
    value: 10000,
    expense: false,
  },
  {
    id: 141,
    category: "ЗП",
    name: "Жены",
    value: 10000,
    expense: false,
  },
  {
    id: 142,
    category: "Доп. доход",
    name: "% с депозита",
    value: 1000,
    expense: false,
  },
  {
    id: 143,
    category: "Доп. доход",
    name: "Подарок на ДР",
    value: 2000,
    expense: false,
  },
  {
    id: 144,
    category: "Доп. доход",
    name: "Ковидная тыща",
    value: 1000,
    expense: false,
  },
];
